AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: Borehole Tracker API

Resources:
  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
         Name: id
         Type: String
      ProvisionedThroughput:
         ReadCapacityUnits: 2
         WriteCapacityUnits: 2

  BoreholeTrackerAPI:
    Type: AWS::Serverless::Function
    StageName: v0
    Properties:
      Handler: bin/lambdaRunner.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: demoTable #!Ref MyTable
          NODE_ENV: dev

      Policies:

      # Give just CRUD permissions
      - DynamoDBCrudPolicy:
          TableName: !Ref MyTable

      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{all+}
            Method: any
        GetEventAtRoot:
          Type: Api
          Properties:
            Path: /
            Method: any
      ReservedConcurrentExecutions: 5